name: receipt-fraud
dependencies:
  - python=3.9
  - pip
  - pip:
      - fastapi
      - uvicorn
      - opencv-python
      - pillow
      - pytesseract
      - scikit-learn
      - numpy
      - pandas
